POST http://localhost:8080/payment
Content-Type: application/json
Authorization: beom

{
  "buyer":
  {
    "buyerName" : "이범기",
    "email" :"qjarl1119@naver.com",
    "phoneNumber":"01090844566"
  },
  "product":
  {
    "productName" : "상품1",
    "price": "1000"
  }
}